import os

print("This is the OS module.")
print("Current working directory:", os.getcwd())
print("List of files in the current directory:", os.listdir('.'))
print("Environment variables:", os.environ)
print("OS name:", os.name)
print("Path separator:", os.pathsep)
print("Path exists:", os.path.exists('.'))
print("Is it a directory?", os.path.isdir('.'))
print("Is it a file?", os.path.isfile(__file__))
print("Absolute path of this script:", os.path.abspath(__file__))  
print("Join paths:", os.path.join('.', 'example.txt'))
print("Split path:", os.path.split(__file__))
print("Split extension:", os.path.splitext(__file__))
print("Normalized path:", os.path.normpath('/foo//bar/baz/../qux/'))
print("Temporary directory:", os.getenv('TMPDIR', '/tmp')) 
print("List of directories in PATH:", os.getenv('PATH').split(os.pathsep))
print("Current user:", os.getenv('USER', 'unknown'))
print("System platform:", os.uname().sysname if hasattr(os, 'uname') else 'Not available')
print("Python version:", os.sys.version)
print("Python executable path:", os.sys.executable)
print("File size of this script:", os.path.getsize(__file__))  
print("File modification time of this script:", os.path.getmtime(__file__)) 